names = ["Shannon", "Tatum", "Charity", "Trevia", "Clayton"]
ages = [37, 36, 30, 39, 29]

people = {}
for n in range(len(names)): # for loop iterates through a list of numbers generated by the range() function
#on each iteration of the loop, the variable n will take on a successive integer from the range() sequence,
# effectively acting as an index or identifier for each person
    people[n] = {# designates n (the current loop index) as the key for the new entry in the people dictionary
# adds a key time to the inner dictionary, and its value is obtained by accessing the n-th element of the names list
        "name": names[n],
# adds a key age to the inner dictionary, and its value is obtained by accessing the n-th element of the ages list
        "age": ages[n]
    }
print(people)# {0: {'name': 'Shannon', 'age': 37}, 1: {'name': 'Tatum', 'age': 36}, 2: {'name': 'Charity', 'age': 30}, 3: {'name': 'Trevia', 'age': 39}, 4: {'name': 'Clayton', 'age': 29}}

# USING DICTIONARY COMPREHENSIONS
my_people = {n: {"name": names[n], "age": ages[n]} for n in range(len(names))}
print(my_people)